name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    
    strategy:    
      matrix:
        cc: [gcc, clang]
        #os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      env:
        CC: ${{ matrix.cc }}

    - name: system info 
      run: sysctl -a

    - name: cpu info  
      run: lscpu
      if: runner.os == 'Linux'
      

    - name: build cmake 
      # github action now use amd chip . rdtsc not expect
      run: |
        mkdir ${{github.workspace}}/build
        cd ${{github.workspace}}/build 
        cmake -DPROF_NO_RDTSC=1 -DCMAKE_BUILD_TYPE=release ../


    - name: make project
      working-directory: ${{github.workspace}}/build
      run: make -j4

    - name: run covarage test 
      working-directory: ${{github.workspace}}/bin
      run: |
          ./fast_direct_using_test
          ./fast_macro_using_test
          ./coverage_format_test
          ./coverage_mini_test
          ./coverage_base_test
          ./coverage_merge_test
          ./coverage_test

    - name: run benchmark test 
      working-directory: ${{github.workspace}}/bin
      run: |
          ./benchmark_branch_prediction_test
          ./benchmark_record_cpu_test
          ./benchmark_compiler_optimization_test
          ./benchmark_cpu_cache_matrix_test
          ./benchmark_cpu_cache_test
          ./benchmark_instructions_cost_test
          ./benchmark_tree_and_array_test

